spring.application.name=pelis

spring.datasource.url=jdbc:oracle:thin:@desarrollofullstack1_tp?TNS_ADMIN=./wallet
spring.datasource.username=fullstack1
spring.datasource.password=Expx_S6_des_fullstack
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#Configuracion del JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000